// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://jobb23cqzjalbgqogvrdwfqo3u.appsync-api.us-east-1.amazonaws.com/graphql',
          region: 'us-east-1',
        defaultAuthMode: 'API_KEY',
          apiKey: 'da2-5wvpy45l6bf3bojobcn4bk75eq'
        }
    }
};

export default config;