projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - app/
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: app
        region: us-east-1
        apiId: 3ixpnq3y2zbwvptr6b6qmbkrqu
        frontend: javascript
        framework: react-native
        maxDepth: 8
