projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - ./
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
        region: us-east-1
        apiId: 3ixpnq3y2zbwvptr6b6qmbkrqu
        frontend: javascript
        framework: react
        maxDepth: 7
extensions:
  amplify:
    version: 3
